name: "Setup Python and Poetry"
description: "Setups Python, Poetry and sets env.project_version"

inputs:
  poetry-version:
    description: "Version of poetry to install"
    required: false
    default: "1.1.14"
  python-version:
    description: "Version of python to install"
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ inputs.python-version }}

        - name: Install poetry
          run: pip install poetry==${{ inputs.poetry-version }}
          shell: bash