name: "Setup Python and Poetry"
description: "Setups Python, Poetry and sets env.project_version"

inputs:
  poetry-version:
    description: "Version of poetry to install"
    required: false
    default: "1.1.14"
  python-version:
    description: "Version of python to install"
    required: false
    default: "3.10"

outputs:
  project-version:
    description: Current project version of pyproject.toml
    value: ${{ steps.setup-poetry.outputs.project-version }}

runs:
  using: "composite"

  steps:
        - name: Setup poetry
          id: setup-poetry
          uses: henningwoehr/actions/setup-poetry@main
          with:
            python-version: ${{ inputs.python-version }}
            poetry-version: ${{ inputs.poetry-version }}
            install-dependencies: true

        - name: Test with pytest in poetry
          run: poetry run pytest
          shell: bash