name: "Setup Python and Poetry"
description: "Setups Python, Poetry and sets env.project_version"

inputs:
  poetry-version:
    description: "Version of poetry to install"
    required: false
    default: "1.1.14"
  python-version:
    description: "Version of python to install"
    required: false
    default: "1.10"

runs:
  using: "composite"
  steps:
        - name: Setup poetry
          uses: henningwoehr/actions/setup-poetry@main
          with:
            python-version: ${{ inputs.python-version }}
            poetry-version: ${{ inputs.poetry-version }}

        - name: Install poetry dependencies
          run: poetry install
          shell: bash

        - name: Test with pytest in poetry
          run: poetry run pytest
          shell: bash